/* ==================== LINHA SEPARADORA ==================== */

SELECT NOME FROM PROFESSORES;

SELECT * FROM PROFESSORES;

SELECT NOME FROM ALUNOS;

SELECT * FROM ALUNOS;

SELECT NOME FROM TURMAS;

SELECT * FROM TURMAS;

/* ==================== LINHA SEPARADORA ==================== */

SELECT NOME FROM ALUNOS WHERE NOME = 'Ana Clara Souza';

/* ==================== LINHA SEPARADORA ==================== */

SELECT NOME FROM ALUNOS ORDER BY NOME;

SELECT NOME FROM ALUNOS ORDER BY NOME DESC;

SELECT NOME FROM ALUNOS ORDER BY NOME ASC;

SELECT * FROM ALUNOS ORDER BY NOME;

/* ==================== LINHA SEPARADORA ==================== */

SELECT NOME, NOTA FROM ALUNOS JOIN NOTAS ON ALUNOS.id = NOTAS.aluno_id;